import './globals.css'
import type { Metadata } from 'next'

import { Inter } from 'next/font/google'

import { ThemeProvider } from '@/components/providers/theme-provider'
import { QueryProvider } from '@/components/providers/query-provider'
import { StateProvider } from '@/components/providers/state-provider'
import { SessionProvider } from 'next-auth/react'
import { auth } from '@/auth'
import SocketProvider from '@/components/providers/socket-provider'
import ModalProvider from '@/components/providers/modal-provider'
import { Toaster } from '@/components/ui/toaster'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  const session = await auth();
  return (
    <SessionProvider session={session} refetchOnWindowFocus>
      <html lang="en" suppressHydrationWarning>
        <body className={`${inter.className} `}>
          <ThemeProvider
            attribute='class'
            defaultTheme='light'
            storageKey='chat-app'
          >
            <SocketProvider>
              <StateProvider>
                <QueryProvider>
                  <ModalProvider />
                  <Toaster />
                  {children}
                </QueryProvider>
              </StateProvider>
            </SocketProvider>
          </ThemeProvider>
        </body>
      </html>
    </SessionProvider>
  )
}
